-- MySQL Script generated by MySQL Workbench
-- Sat Jan  2 02:30:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema stripe_db
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  `sexe` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL,
  `date_naissance` DATE NOT NULL,
  `creation` DATE NULL,
  `modification` DATE NULL,
  `Abonnement` INT NULL,
  PRIMARY KEY (`id_utilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tuteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tuteur` (
  `id_tuteur` INT NOT NULL AUTO_INCREMENT,
  `fk_id_utilisateur_tuteur` INT NULL,
  PRIMARY KEY (`id_tuteur`),
  INDEX `fk_id_utilisateur_tuteur_idx` (`fk_id_utilisateur_tuteur` ASC) VISIBLE,
  CONSTRAINT `fk_id_utilisateur_tuteur`
    FOREIGN KEY (`fk_id_utilisateur_tuteur`)
    REFERENCES `mydb`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enfant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enfant` (
  `id_enfant` INT NOT NULL AUTO_INCREMENT,
  `cvc` VARCHAR(45) NULL,
  `fk_id_utilisateur_enfant` INT NULL,
  PRIMARY KEY (`id_enfant`),
  INDEX `fk_id_utilisateur_idx` (`fk_id_utilisateur_enfant` ASC) VISIBLE,
  CONSTRAINT `fk_id_utilisateur_enfant`
    FOREIGN KEY (`fk_id_utilisateur_enfant`)
    REFERENCES `mydb`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carte` (
  `id_carte` INT NOT NULL AUTO_INCREMENT,
  `numero_carte` INT NOT NULL,
  `mois` INT NOT NULL,
  `annee` INT NOT NULL,
  `defaut` TINYINT NOT NULL,
  `Utilisateur_idUtilisateur` INT NULL,
  PRIMARY KEY (`id_carte`),
  INDEX `fk_Carte_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Carte_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stripe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stripe` (
  `id_stripe` INT NOT NULL AUTO_INCREMENT,
  `Carte_id_carte` INT NOT NULL,
  PRIMARY KEY (`id_stripe`, `Carte_id_carte`),
  INDEX `fk_Stripe_Carte1_idx` (`Carte_id_carte` ASC) VISIBLE,
  CONSTRAINT `fk_Stripe_Carte1`
    FOREIGN KEY (`Carte_id_carte`)
    REFERENCES `mydb`.`Carte` (`id_carte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facture` (
  `id_facture` INT NOT NULL AUTO_INCREMENT,
  `id_stripe` INT NULL,
  `date_facture` DATE NULL,
  `montant_ht` FLOAT NULL,
  `montant_ttc` FLOAT NULL,
  `source` VARCHAR(45) NULL,
  `creation` DATE NULL,
  `modification` DATE NULL,
  `Stripe_id_stripe` INT NOT NULL,
  PRIMARY KEY (`id_facture`, `Stripe_id_stripe`),
  INDEX `fk_Facture_Stripe1_idx` (`Stripe_id_stripe` ASC) VISIBLE,
  CONSTRAINT `fk_Facture_Stripe1`
    FOREIGN KEY (`Stripe_id_stripe`)
    REFERENCES `mydb`.`Stripe` (`id_stripe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Musiques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musiques` (
  `id_musique` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `couverture` VARCHAR(45) NULL,
  `temps` INT NULL,
  `creation` DATE NULL,
  `modification` DATE NULL,
  `type` INT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`id_musique`, `Utilisateur_idUtilisateur`),
  INDEX `fk_Musiques_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Musiques_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Créer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Créer` (
  `Tuteur_id_tuteur` INT NOT NULL,
  `Enfant_id_enfant` INT NOT NULL,
  PRIMARY KEY (`Tuteur_id_tuteur`, `Enfant_id_enfant`),
  INDEX `fk_Tuteur_has_Enfant_Enfant1_idx` (`Enfant_id_enfant` ASC) VISIBLE,
  INDEX `fk_Tuteur_has_Enfant_Tuteur1_idx` (`Tuteur_id_tuteur` ASC) VISIBLE,
  CONSTRAINT `fk_Tuteur_has_Enfant_Tuteur1`
    FOREIGN KEY (`Tuteur_id_tuteur`)
    REFERENCES `mydb`.`Tuteur` (`id_tuteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tuteur_has_Enfant_Enfant1`
    FOREIGN KEY (`Enfant_id_enfant`)
    REFERENCES `mydb`.`Enfant` (`id_enfant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
